query multiple tables
atatm/vet_clinic pull request #4
Opened 2023-02-22 13:05 UTC by atatm

![Screenshot (39)](https://user-images.githubusercontent.com/106224524/220627702-02f7e299-f797-4ca9-8a41-4c8830351e9d.png)
![Screenshot (34)](https://user-images.githubusercontent.com/106224524/220627710-dd5d78e9-3371-48ba-b627-b5b91af1d935.png)
![Screenshot (35)](https://user-images.githubusercontent.com/106224524/220627712-9d2b8c73-56d8-45c0-9076-9d1b368c91dc.png)
![Screenshot (36)](https://user-images.githubusercontent.com/106224524/220627680-9cc85b78-8b87-4e58-9fa5-b348130f5652.png)
![Screenshot (37)](https://user-images.githubusercontent.com/106224524/220627691-d932a095-a105-4417-8f70-6a1ec0c7a901.png)
![Screenshot (38)](https://user-images.githubusercontent.com/106224524/220627697-8e08725e-3f07-42a8-a633-b640d7172ce8.png)

2023-02-22 13:27 UTC, rloterh requested changes
Hi Alelign, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦   🏃 

## Highlights 👍  
- Good job so far implementing queries for multiple tables!

## Required Changes ♻️
- [ ] Kindly ensure to remove redundant demo links in your ReadMe.
- [ ] MIT license link in your ReadMe is broken, kindly endeavor to fix it, and remove the guide note below it.

_Kindly check the other inline comments under the review._

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 13:27 UTC, rloterh commented on queries.sql
> +
- [ ] Queries for _Who owns the most animals?_ is missing! Kindly ensure to include them, which should be similar to:

```sql
SELECT owners.full_name, COUNT(owners.full_name) FROM animals
   LEFT JOIN owners
   ON animals.species_id = owners.id
   GROUP BY owners.full_name
   ORDER BY COUNT(owners.full_name) DESC
```

2023-02-23 07:33 UTC, Davidosky007 requested changes
Hi @atatm 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
* Well written PR description 👍 
* Proper use of Gitflow 👍 

 ## Required Changes ♻️
* As mentioned by the previous CR , kindly remove the live demo link on your readme file as this project doesn't have one 
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidosky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 07:52 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @atatm ✋

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Highlights!
- Followed Gitflow ✔️
- Good commit messages ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-23 07:58 UTC, merged